version: 0.2

phases:

  install:
    runtime-versions:
      java: "corretto8"

  pre_build:
    commands:
    - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain amazon --domain-owner 149122183214 --region us-west-2 --query authorizationToken --output text`

  build:
    commands:
    - mvn -s resources/release-settings.xml compile
artifacts:
  files:
    - aws-java-sdk-osgi/target/aws-java-sdk.zip
    - pom.xml
    - release-resources/buildspecs/*.yml
